# kubernetes/identity-service/01-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service-sa
  namespace: masiryar-production
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: masiryar-identity-service
    app.kubernetes.io/part-of: masiryar
