# kubernetes/api-gateway/01-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: masiryar-production
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: masiryar-api-gateway
    app.kubernetes.io/part-of: masiryar
