# kubernetes/api-gateway/03-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: masiryar-production
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: masiryar-api-gateway
    app.kubernetes.io/part-of: masiryar
type: Opaque
data:
  # Add any sensitive data here, Base64 encoded.
  ApiKey: "UGxhY2Vob2xkZXI=" # Placeholder
